package com.adg.networking.models;

import com.google.gson.annotations.SerializedName;

public class Post
{
    private int userId;
    /*
     * In order to be nullable
     * the wrapper class needs to be
     * used. In this way retrofit will
     * omit any null parameters in a given
     * http request; Also when serializing,
     * GSON will set it to null when not given
     * any value and the final json text will not
     * contain the respective field.
     */
    private Integer id;
    private String title;
    /*
     * Annotation because the field
     * name and the json field differ
     */
    @SerializedName("body")
    private String text;

    /* Used to create post requests, id will be generated by API */
    public Post(int userId, String title, String text) {
        this.userId = userId;
        this.title = title;
        this.text = text;
    }

    public int getUserId() {
        return userId;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getText() {
        return text;
    }
}
